fixup meson build
Signed-off-by: Keith Wiles <keith.wiles@intel.com>

diff --git a/mk_meson b/mk_meson
--- a/mk_meson
+++ b/mk_meson
@@ -1,36 +1,38 @@
 #!/bin/bash
 
 function meson_bld() {
-	echo "Clean Pktgen"
-	rm -fr build
+	echo "Clean install directory!"
+	rm -fr build work $RTE_TARGET
 
-	meson build
+	meson --prefix=/$RTE_TARGET build
 }
 
 function ninja_build() {
-	echo "Do Pktgen build"
+	echo "Do Ninja in build directory"
 
 	ninja -C build
 
-	if [ $? -ne 0 ] ; then
-	       return 1;
+	if [[ $? -ne 0 ]]; then
+		echo "Build failed!!!"
+		return 1;
         fi
 	return 0       
 }
 
 ninja_install() {
-	echo "Do install to $RTE_SDK/$RTE_TARGET"
+	echo "Do Ninja install to $RTE_SDK/$RTE_TARGET"
 
 	DESTDIR=$RTE_SDK ninja -C build install > /dev/null
 
-	if [ $? -ne 0 ] ; then
+	if [[ $? -ne 0 ]]; then
 		echo "Install failed!!"
 	       return 1;
         fi
+	touch $RTE_SDK/$RTE_TARGET/.config
 	return 0       
 }
 
 if [ $# -gt 0 ]; then
 	meson_bld
 fi
-ninja_build
+ninja_build && ninja_install
